name: Create Release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Auth Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - id: git-user
        name: Set up git user
        uses: haarg/setup-git-user@v1
        with:
          app: ${{ steps.app-token.outputs.app-slug }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Find Previous Tag
        id: prev-tag
        run: ./maint/prev-release
      - name: Fetch Previous Tag
        run: git fetch origin ${{ steps.prev-tag.outputs.tag-name }}:refs/tags/${{ steps.prev-tag.outputs.tag-name }}
      - name: Prepare Release
        id: prepare-release
        run: ./maint/prepare-release
      - run: |
          git push origin HEAD ${{ steps.prepare-release.outputs.tag-name }}
