name: Keepalive Workflow
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  actions: write
jobs:
  cronjob-based-github-action:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          workflow_files: "update-mk-ca-bundle.yml, update-cacert-file.yml"
          time_elapsed: 0
