name: Create release on tag upload

on:
  push:
    tags:
      - 'v*'

jobs:
  make-release:
    if: github.repository_owner == 'libwww-perl'
    runs-on: ubuntu-latest
    steps:
      - name: Generate Auth Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Install cpan-upload-tiny
        run: |
          echo "$HOME/perl5/bin" >> "$GITHUB_PATH"
          echo "PERL5LIB=$HOME/perl5/lib/perl5" >> "$GITHUB_ENV"
          echo "PERL_MM_OPT=INSTALL_BASE=$HOME/perl5" >> "$GITHUB_ENV"
          echo "PERL_MB_OPT=--install_base $HOME/perl5" >> "$GITHUB_ENV"
          curl -s https://cpanmin.us/ | perl - -n CPAN::Upload::Tiny
      - name: Set up PAUSE credentials
        env:
          PAUSE_USER: ${{ vars.PAUSE_USER }}
          PAUSE_PASS: ${{ secrets.PAUSE_PASS }}
        run: |
          printf "user $PAUSE_USER\npassword $PAUSE_PASS\n" > "$HOME/.pause"
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Build Release
        id: build
        run: |
          perl Makefile.PL
          make manifest
          make tardist
          echo "tarball=$(./maint/get-tarball-name)" >> "$GITHUB_OUTPUT"
      - name: Upload to PAUSE
        run: cpan-upload-tiny ${{ steps.build.outputs.tarball }}
      - name: Get tag content
        id: tag-content
        run: |
          EOF="$(dd if=/dev/urandom bs=15 count=1 status=none | base64)"
          echo "tag-content<<$EOF" >> "$GITHUB_OUTPUT"
          git tag -l --format='%(contents)' "$GITHUB_REF_NAME" >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ steps.app-token.outputs.token }}
          files: ${{ steps.build.outputs.tarball }}
          body: ${{ steps.tag-content.outputs.tag-content }}
