---
name: build and test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-job:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run Makefile.PL
        run: perl Makefile.PL
      - name: make manifest
        run: make manifest
      - name: build dist
        run: make distdir DISTVNAME=build_dir
      - uses: actions/upload-artifact@v4
        with:
          name: build_dir
          path: build_dir
          if-no-files-found: error
  test-job:
    needs: build-job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        perl-version:
          - "5.38"
    name: perl ${{ matrix.perl-version }} on ${{ matrix.os }}
    steps:
      - name: set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
      - uses: actions/download-artifact@v4
        with:
          name: build_dir
      - name: install deps using cpm
        uses: perl-actions/install-with-cpm@v1
      - run: prove -lr t
