name: Update cacert.pem file

on:
  schedule:
    - cron: "33 16 * * *"
  workflow_dispatch:

jobs:
  update-cacert-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update cacert.pem file
        run: |
          ./maint/update-cacert-file
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update certificate bundle
          title: Update certificate bundle
          branch: update-cacert-file
