name: Update cacert.pem file

on:
  schedule:
    - cron: "33 16 * * *"
  workflow_dispatch:

jobs:
  update-cacert-file:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Auth Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - id: git-user
        name: Set up git user
        uses: haarg/setup-git-user@v1
        with:
          app: ${{ steps.app-token.outputs.app-slug }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Update cacert.pem file
        run: |
          ./maint/update-cacert-file
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: Update certificate bundle
          author: ${{ steps.git-user.outputs.user-full }}
          committer: ${{ steps.git-user.outputs.user-full }}
          title: Update certificate bundle
          branch: update-cacert-file
