name: update mk-ca-bundle script

on:
  schedule:
    - cron: "14 15 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: update cacert file
        run: |
          ./maint/update-mk-ca-bundle
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update certificate bundle
          title: Update certificate bundle
          branch: update-mk-ca-bundle
